-- NSIA Call Center - création des tables Supabase
-- À exécuter une seule fois dans Supabase > SQL Editor.

create table if not exists public.appels_call_center (
    id bigint generated by default as identity primary key,
    call_date date not null default current_date,
    to_name text not null,
    client_name text,
    phone text,
    registration_number text,
    policy_number text,
    campaign text not null,
    reception text not null,
    call_answer text,
    existing_product text,
    proposed_product text,
    desired_product text,
    point_of_sale text,
    call_time time,
    status text,
    no_answer_reason text,
    satisfaction text,
    recommendation text,
    feedback text,
    comment text,
    revenue numeric(18,2) not null default 0,
    version integer not null default 1,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint calls_to_not_blank check (length(trim(to_name)) > 0),
    constraint calls_campaign_not_blank check (length(trim(campaign)) > 0),
    constraint calls_reception_not_blank check (length(trim(reception)) > 0),
    constraint calls_revenue_nonnegative check (revenue >= 0),
    constraint calls_version_positive check (version > 0)
);

create table if not exists public.references_call_center (
    id bigint generated by default as identity primary key,
    value text not null,
    reference_type text not null,
    active boolean not null default true,
    sort_order integer not null default 999999,
    version integer not null default 1,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint references_value_not_blank check (length(trim(value)) > 0),
    constraint references_type_not_blank check (length(trim(reference_type)) > 0),
    constraint references_version_positive check (version > 0)
);

create unique index if not exists references_call_center_unique_value
    on public.references_call_center (lower(reference_type), lower(value));

create index if not exists appels_call_center_date_idx
    on public.appels_call_center (call_date desc);
create index if not exists appels_call_center_to_idx
    on public.appels_call_center (to_name);
create index if not exists appels_call_center_campaign_idx
    on public.appels_call_center (campaign);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists appels_call_center_set_updated_at
    on public.appels_call_center;
create trigger appels_call_center_set_updated_at
before update on public.appels_call_center
for each row execute function public.set_updated_at();

drop trigger if exists references_call_center_set_updated_at
    on public.references_call_center;
create trigger references_call_center_set_updated_at
before update on public.references_call_center
for each row execute function public.set_updated_at();

alter table public.appels_call_center enable row level security;
alter table public.references_call_center enable row level security;

-- Aucune lecture ou écriture directe avec une clé publique.
-- Seul le serveur Streamlit, avec la clé secrète, accède aux tables.
revoke all on table public.appels_call_center from anon, authenticated;
revoke all on table public.references_call_center from anon, authenticated;
grant all on table public.appels_call_center to service_role;
grant all on table public.references_call_center to service_role;
grant usage, select on all sequences in schema public to service_role;

insert into public.references_call_center
    (value, reference_type, active, sort_order)
values
    ('Audrey', 'TO', true, 1),
    ('Sylvanus', 'TO', true, 2),
    ('Florentina', 'TO', true, 3),
    ('SATURATION', 'CAMPAGNE', true, 1),
    ('RELANCE', 'CAMPAGNE', true, 2),
    ('RECUPERATION', 'CAMPAGNE', true, 3),
    ('ONBOARDING', 'CAMPAGNE', true, 4),
    ('RECEPTION', 'CAMPAGNE', true, 5),
    ('REN', 'RECEPTION', true, 1),
    ('AFN', 'RECEPTION', true, 2),
    ('Oui', 'PRISE_APPEL', true, 1),
    ('Non', 'PRISE_APPEL', true, 2),
    ('Injoignable', 'PRISE_APPEL', true, 3)
on conflict do nothing;

notify pgrst, 'reload schema';
